MAIL_SERVER = 'smtp.qq.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = '1374198709@qq.com'
MAIL_PASSWORD = 'hbcydrfoszmngjgd'
TARGET_EMAIL = '1440138181@qq.com'

SQLALCHEMY_DATABASE_URI = 'sqlite:///menu.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
