MAIL_SERVER = 'smtp.qq.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = '你的QQ邮箱@qq.com'
MAIL_PASSWORD = '你的SMTP授权码'
TARGET_EMAIL = '接收订单的邮箱@qq.com'

SQLALCHEMY_DATABASE_URI = 'sqlite:///menu.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
